/// Generate the `compliance_helpers.rb` support file content.
///
/// This file provides helper methods that the generated RSpec tests call
/// to interact with system resources without requiring InSpec CLI.
#[must_use]
pub fn generate_helpers() -> String {
    r##"# Generated by inspec-rspec
# DO NOT EDIT — regenerate with: inspec-rspec transpile <profile>
#
# ComplianceHelpers provides system resource access methods that replace
# InSpec's built-in resources. Tests run without InSpec CLI or cloud access.

module ComplianceHelpers
  # Read and parse a configuration file into a key-value hash.
  #
  # Handles common config formats:
  # - key value (sshd_config style)
  # - key=value (sysctl style)
  # - key: value (YAML-like)
  #
  # @param path [String] absolute path to the config file
  # @return [Hash] parsed key-value pairs
  def self.read_config(path)
    result = {}
    return result unless File.exist?(path)

    File.readlines(path).each do |line|
      line = line.strip
      next if line.empty? || line.start_with?('#')

      if line.include?('=')
        key, value = line.split('=', 2).map(&:strip)
      elsif line.include?(': ')
        key, value = line.split(': ', 2).map(&:strip)
      else
        parts = line.split(/\s+/, 2)
        key = parts[0]
        value = parts[1]
      end

      result[key] = value if key && !key.empty?
    end

    result
  end

  # Execute a command and return structured output.
  #
  # @param cmd [String] the command to execute
  # @return [Hash] with keys 'stdout', 'stderr', 'exit_status'
  def self.command_output(cmd)
    require 'open3'
    stdout, stderr, status = Open3.capture3(cmd)
    {
      'stdout' => stdout.strip,
      'stderr' => stderr.strip,
      'exit_status' => status.exitstatus
    }
  end

  # Read file contents.
  #
  # @param path [String] absolute path to the file
  # @return [Hash] with keys 'content', 'exists', 'owner', 'mode'
  def self.file_content(path)
    if File.exist?(path)
      stat = File.stat(path)
      {
        'content' => File.read(path),
        'exists' => true,
        'owner' => Etc.getpwuid(stat.uid).name,
        'mode' => sprintf('%04o', stat.mode & 0o7777)
      }
    else
      {
        'content' => '',
        'exists' => false,
        'owner' => nil,
        'mode' => nil
      }
    end
  end

  # Check service status.
  #
  # @param name [String] service name
  # @return [Hash] with keys 'running', 'enabled'
  def self.service_status(name)
    running = system("systemctl is-active --quiet #{name} 2>/dev/null")
    enabled = system("systemctl is-enabled --quiet #{name} 2>/dev/null")
    {
      'running' => running || false,
      'enabled' => enabled || false
    }
  end

  # Check package installation status.
  #
  # @param name [String] package name
  # @return [Hash] with keys 'installed', 'version'
  def self.package_info(name)
    result = command_output("dpkg -s #{name} 2>/dev/null || rpm -q #{name} 2>/dev/null")
    installed = result['exit_status'] == 0
    version = nil
    if installed
      result['stdout'].each_line do |line|
        if line =~ /^Version:\s*(.+)/
          version = $1.strip
          break
        end
      end
    end
    {
      'installed' => installed,
      'version' => version
    }
  end

  # Check listening ports.
  #
  # @param port [Integer, String] port number
  # @return [Hash] with keys 'listening', 'protocol', 'process'
  def self.port_info(port)
    result = command_output("ss -tlnp sport = :#{port} 2>/dev/null")
    listening = result['exit_status'] == 0 && result['stdout'].include?(port.to_s)
    {
      'listening' => listening,
      'protocol' => nil,
      'process' => nil
    }
  end

  # Get user information.
  #
  # @param name [String] username
  # @return [Hash] with keys 'exists', 'uid', 'gid', 'home', 'shell'
  def self.user_info(name)
    require 'etc'
    begin
      pw = Etc.getpwnam(name)
      {
        'exists' => true,
        'uid' => pw.uid,
        'gid' => pw.gid,
        'home' => pw.dir,
        'shell' => pw.shell
      }
    rescue ArgumentError
      {
        'exists' => false,
        'uid' => nil,
        'gid' => nil,
        'home' => nil,
        'shell' => nil
      }
    end
  end

  # Get group information.
  #
  # @param name [String] group name
  # @return [Hash] with keys 'exists', 'gid', 'members'
  def self.group_info(name)
    require 'etc'
    begin
      gr = Etc.getgrnam(name)
      {
        'exists' => true,
        'gid' => gr.gid,
        'members' => gr.mem
      }
    rescue ArgumentError
      {
        'exists' => false,
        'gid' => nil,
        'members' => []
      }
    end
  end

  # Read a kernel parameter value.
  #
  # @param param [String] kernel parameter name (e.g., 'net.ipv4.ip_forward')
  # @return [Hash] with key matching the parameter name
  def self.kernel_parameter(param)
    result = command_output("sysctl -n #{param} 2>/dev/null")
    { param => result['stdout'] }
  end

  # Generic resource fallback.
  #
  # @param args [Array] resource arguments
  # @return [Hash] empty hash
  def self.generic_resource(*args)
    { 'args' => args, 'available' => false }
  end
end
"##
    .to_string()
}

/// Generate the `spec_helper.rb` content for a profile.
#[must_use]
pub fn generate_spec_helper(profile_name: &str) -> String {
    format!(
        r#"# Generated by inspec-rspec for profile: {profile_name}
# DO NOT EDIT — regenerate with: inspec-rspec transpile <profile>

require_relative 'compliance_helpers'

RSpec.configure do |config|
  config.formatter = :documentation
  config.color = true
  config.order = :defined

  # Add profile metadata
  config.before(:suite) do
    puts "Compliance Profile: {profile_name}"
    puts "Generated by: inspec-rspec"
    puts ""
  end

  # JSON output for attestation hashing
  config.after(:suite) do |_example|
    if ENV['COMPLIANCE_JSON_OUTPUT']
      require 'json'
      results = {{
        profile: '{profile_name}',
        timestamp: Time.now.utc.iso8601,
        generator: 'inspec-rspec',
        results: []
      }}
      File.write(ENV['COMPLIANCE_JSON_OUTPUT'], JSON.pretty_generate(results))
    end
  end
end
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn helpers_contains_module() {
        let content = generate_helpers();
        assert!(content.contains("module ComplianceHelpers"));
    }

    #[test]
    fn helpers_contains_read_config() {
        let content = generate_helpers();
        assert!(content.contains("def self.read_config(path)"));
    }

    #[test]
    fn helpers_contains_command_output() {
        let content = generate_helpers();
        assert!(content.contains("def self.command_output(cmd)"));
    }

    #[test]
    fn helpers_contains_file_content() {
        let content = generate_helpers();
        assert!(content.contains("def self.file_content(path)"));
    }

    #[test]
    fn helpers_contains_service_status() {
        let content = generate_helpers();
        assert!(content.contains("def self.service_status(name)"));
    }

    #[test]
    fn helpers_contains_package_info() {
        let content = generate_helpers();
        assert!(content.contains("def self.package_info(name)"));
    }

    #[test]
    fn helpers_contains_header() {
        let content = generate_helpers();
        assert!(content.contains("Generated by inspec-rspec"));
        assert!(content.contains("DO NOT EDIT"));
    }

    #[test]
    fn helpers_deterministic() {
        let a = generate_helpers();
        let b = generate_helpers();
        assert_eq!(a, b);
    }

    #[test]
    fn spec_helper_contains_profile_name() {
        let content = generate_spec_helper("ssh-baseline");
        assert!(content.contains("ssh-baseline"));
    }

    #[test]
    fn spec_helper_contains_rspec_config() {
        let content = generate_spec_helper("test");
        assert!(content.contains("RSpec.configure"));
    }

    #[test]
    fn spec_helper_json_output() {
        let content = generate_spec_helper("test");
        assert!(content.contains("COMPLIANCE_JSON_OUTPUT"));
    }

    #[test]
    fn spec_helper_deterministic() {
        let a = generate_spec_helper("test-profile");
        let b = generate_spec_helper("test-profile");
        assert_eq!(a, b);
    }
}
