use crate::control::{InSpecControl, InSpecMatcher, InSpecTag};

/// A generated RSpec test file.
#[derive(Clone, Debug)]
pub struct RSpecFile {
    /// Output filename (e.g., `sshd_01_spec.rb`).
    pub filename: String,

    /// Generated Ruby source content.
    pub content: String,

    /// The control ID this file was generated from.
    pub control_id: String,
}

/// Resource type to `ComplianceHelpers` method mapping.
struct ResourceMapping {
    helper_method: &'static str,
    default_arg: &'static str,
}

/// Map InSpec resource types to `ComplianceHelpers` methods.
fn resource_mapping(resource_type: &str) -> ResourceMapping {
    match resource_type {
        "sshd_config" => ResourceMapping {
            helper_method: "read_config",
            default_arg: "/etc/ssh/sshd_config",
        },
        "file" => ResourceMapping {
            helper_method: "file_content",
            default_arg: "",
        },
        "command" => ResourceMapping {
            helper_method: "command_output",
            default_arg: "",
        },
        "service" => ResourceMapping {
            helper_method: "service_status",
            default_arg: "",
        },
        "package" => ResourceMapping {
            helper_method: "package_info",
            default_arg: "",
        },
        "port" => ResourceMapping {
            helper_method: "port_info",
            default_arg: "",
        },
        "user" => ResourceMapping {
            helper_method: "user_info",
            default_arg: "",
        },
        "group" => ResourceMapping {
            helper_method: "group_info",
            default_arg: "",
        },
        "kernel_parameter" => ResourceMapping {
            helper_method: "kernel_parameter",
            default_arg: "",
        },
        _ => ResourceMapping {
            helper_method: "generic_resource",
            default_arg: "",
        },
    }
}

/// Transpile a single InSpec control to an RSpec test file.
///
/// Generates deterministic output: same input always produces identical output.
#[must_use]
pub fn transpile_control(control: &InSpecControl) -> RSpecFile {
    let filename = control_id_to_filename(&control.id);
    let content = generate_rspec_content(control);

    RSpecFile {
        filename,
        content,
        control_id: control.id.clone(),
    }
}

/// Transpile all controls from a profile into RSpec files.
#[must_use]
pub fn transpile_profile(controls: &[InSpecControl], _profile_name: &str) -> Vec<RSpecFile> {
    controls.iter().map(transpile_control).collect()
}

/// Convert a control ID to a valid Ruby filename.
///
/// `"sshd-01"` → `"sshd_01_spec.rb"`
#[must_use]
pub fn control_id_to_filename(id: &str) -> String {
    let sanitized: String = id
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    format!("{sanitized}_spec.rb")
}

/// Generate the full RSpec file content for a control.
fn generate_rspec_content(control: &InSpecControl) -> String {
    let mut out = String::new();

    // Header comments
    out.push_str(&format!(
        "# Generated by inspec-rspec from control '{}'\n",
        control.id
    ));
    out.push_str(&format!("# Source: {}\n", control.source_file));
    out.push_str("# DO NOT EDIT — regenerate with: inspec-rspec transpile <profile>\n");
    out.push('\n');
    out.push_str("require 'compliance_helpers'\n");
    out.push('\n');

    // RSpec.describe block
    let title_escaped = control.title.replace('\'', "\\'");
    out.push_str(&format!(
        "RSpec.describe '{}: {}' do\n",
        control.id, title_escaped
    ));

    // Metadata
    out.push_str(&format!("  metadata[:impact] = {}\n", format_impact(control.impact)));

    for tag in &control.tags {
        out.push_str(&format!("  metadata[:{}] = {}\n", tag.key, format_tag_value(tag)));
    }

    if !control.description.is_empty() {
        let desc_escaped = control.description.replace('\'', "\\'");
        out.push_str(&format!("  metadata[:description] = '{}'\n", desc_escaped));
    }

    out.push('\n');

    // Test blocks
    if control.tests.is_empty() {
        out.push_str("  it 'is documented (no automated tests)' do\n");
        out.push_str("    skip 'No automated tests defined for this control'\n");
        out.push_str("  end\n");
    } else {
        for (test_idx, test) in control.tests.iter().enumerate() {
            generate_test_block(&mut out, control, test, test_idx);
        }
    }

    out.push_str("end\n");
    out
}

/// Generate a test block (it/describe) for a single InSpec test.
fn generate_test_block(
    out: &mut String,
    control: &InSpecControl,
    test: &crate::control::InSpecTest,
    test_idx: usize,
) {
    let mapping = resource_mapping(&test.resource_type);

    // Comment showing the InSpec resource
    out.push_str(&format!(
        "  # InSpec resource: {}{}\n",
        test.resource_type,
        if test.resource_args.is_empty() {
            String::new()
        } else {
            format!("({})", test.resource_args)
        }
    ));

    if test.matchers.is_empty() {
        out.push_str(&format!(
            "  it 'validates {} (test {})' do\n",
            test.resource_type,
            test_idx + 1
        ));
        out.push_str("    skip 'No matchers defined'\n");
        out.push_str("  end\n\n");
        return;
    }

    for (matcher_idx, matcher) in test.matchers.iter().enumerate() {
        let test_description = build_test_description(control, matcher, matcher_idx);
        let assertion = build_assertion(matcher, &test.resource_type, &test.resource_args, mapping.helper_method, mapping.default_arg);

        out.push_str(&format!(
            "  # Assertion: {}\n",
            matcher.raw_line
        ));
        out.push_str(&format!("  it '{}' do\n", test_description.replace('\'', "\\'")));
        out.push_str(&format!("    {assertion}\n"));
        out.push_str("  end\n\n");
    }
}

/// Build a human-readable test description from a matcher.
fn build_test_description(
    _control: &InSpecControl,
    matcher: &InSpecMatcher,
    _idx: usize,
) -> String {
    let negation = if matcher.negated { " not" } else { "" };

    if let Some(ref prop) = matcher.property {
        format!("{prop} should{negation} {}", matcher.expectation)
    } else {
        format!("should{negation} {}", matcher.expectation)
    }
}

/// Build the RSpec assertion code for a matcher.
fn build_assertion(
    matcher: &InSpecMatcher,
    _resource_type: &str,
    resource_args: &str,
    helper_method: &str,
    default_arg: &str,
) -> String {
    let arg = if resource_args.is_empty() {
        if default_arg.is_empty() {
            String::new()
        } else {
            format!("'{default_arg}'")
        }
    } else {
        clean_resource_arg(resource_args)
    };

    let resource_call = if arg.is_empty() {
        format!("ComplianceHelpers.{helper_method}")
    } else {
        format!("ComplianceHelpers.{helper_method}({arg})")
    };

    let (rspec_matcher, value) = translate_expectation(&matcher.expectation);
    let negation = if matcher.negated { "_not" } else { "" };

    if let Some(ref prop) = matcher.property {
        if let Some(ref val) = value {
            format!(
                "result = {resource_call}\n    expect(result['{prop}']).to{negation} {rspec_matcher}({val})"
            )
        } else {
            format!(
                "result = {resource_call}\n    expect(result['{prop}']).to{negation} {rspec_matcher}"
            )
        }
    } else if let Some(ref val) = value {
        format!(
            "result = {resource_call}\n    expect(result).to{negation} {rspec_matcher}({val})"
        )
    } else {
        format!(
            "result = {resource_call}\n    expect(result).to{negation} {rspec_matcher}"
        )
    }
}

/// Translate an InSpec expectation to an RSpec matcher + optional value.
fn translate_expectation(expectation: &str) -> (String, Option<String>) {
    let trimmed = expectation.trim();

    // cmp VALUE  or  cmp OP VALUE
    if trimmed.starts_with("cmp ") {
        let rest = &trimmed[4..];
        // cmp <= 4, cmp >= 1, cmp < 10, cmp > 0
        if rest.starts_with("<=") || rest.starts_with(">=") || rest.starts_with('<') || rest.starts_with('>') {
            let (op, val) = if rest.starts_with("<=") || rest.starts_with(">=") {
                (&rest[..2], rest[2..].trim())
            } else {
                (&rest[..1], rest[1..].trim())
            };
            let rspec_op = match op {
                "<=" => "be <=",
                ">=" => "be >=",
                "<" => "be <",
                ">" => "be >",
                _ => "eq",
            };
            return (rspec_op.to_string(), Some(val.to_string()));
        }
        return ("eq".to_string(), Some(rest.trim().to_string()));
    }

    // eq VALUE
    if trimmed.starts_with("eq ") {
        return ("eq".to_string(), Some(trimmed[3..].trim().to_string()));
    }

    // match /regex/
    if trimmed.starts_with("match ") {
        let pattern = trimmed[6..].trim();
        return ("match".to_string(), Some(pattern.to_string()));
    }

    // be_installed, be_running, be_enabled, exist, etc.
    (format!("be_{}", trimmed.trim_start_matches("be_")), None)
}

/// Clean up resource arguments (remove surrounding quotes if present).
fn clean_resource_arg(arg: &str) -> String {
    let trimmed = arg.trim();
    // If already quoted, return as-is for Ruby
    if (trimmed.starts_with('\'') && trimmed.ends_with('\''))
        || (trimmed.starts_with('"') && trimmed.ends_with('"'))
    {
        return trimmed.to_string();
    }
    format!("'{trimmed}'")
}

/// Format an impact score for Ruby output.
fn format_impact(impact: f64) -> String {
    if (impact - impact.round()).abs() < f64::EPSILON {
        format!("{impact:.1}")
    } else {
        format!("{impact}")
    }
}

/// Format a tag value for Ruby output.
fn format_tag_value(tag: &InSpecTag) -> String {
    if tag.values.len() == 1 {
        format!("'{}'", tag.values[0])
    } else {
        let items: Vec<String> = tag.values.iter().map(|v| format!("'{v}'")).collect();
        format!("[{}]", items.join(", "))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::control::{InSpecControl, InSpecMatcher, InSpecTag, InSpecTest};

    fn sample_control() -> InSpecControl {
        InSpecControl {
            id: "sshd-01".to_string(),
            impact: 1.0,
            title: "SSH Protocol Version".to_string(),
            description: "Ensure SSH Protocol is set to 2".to_string(),
            tags: vec![
                InSpecTag {
                    key: "nist".to_string(),
                    values: vec!["AC-17(2)".to_string(), "SC-8".to_string()],
                },
                InSpecTag {
                    key: "cis".to_string(),
                    values: vec!["5.2.1".to_string()],
                },
            ],
            tests: vec![InSpecTest {
                resource_type: "sshd_config".to_string(),
                resource_args: String::new(),
                matchers: vec![InSpecMatcher {
                    property: Some("Protocol".to_string()),
                    expectation: "cmp 2".to_string(),
                    negated: false,
                    raw_line: "its('Protocol') { should cmp 2 }".to_string(),
                }],
            }],
            source_file: "controls/ssh_config.rb".to_string(),
            source_line: 1,
        }
    }

    #[test]
    fn transpile_single_control() {
        let control = sample_control();
        let result = transpile_control(&control);

        assert_eq!(result.control_id, "sshd-01");
        assert_eq!(result.filename, "sshd_01_spec.rb");
        assert!(result.content.contains("RSpec.describe"));
    }

    #[test]
    fn transpile_generates_header() {
        let control = sample_control();
        let result = transpile_control(&control);

        assert!(result.content.contains("Generated by inspec-rspec from control 'sshd-01'"));
        assert!(result.content.contains("Source: controls/ssh_config.rb"));
        assert!(result.content.contains("DO NOT EDIT"));
    }

    #[test]
    fn transpile_generates_metadata() {
        let control = sample_control();
        let result = transpile_control(&control);

        assert!(result.content.contains("metadata[:impact] = 1.0"));
        assert!(result.content.contains("metadata[:nist] = ['AC-17(2)', 'SC-8']"));
        assert!(result.content.contains("metadata[:cis] = '5.2.1'"));
    }

    #[test]
    fn transpile_generates_it_block() {
        let control = sample_control();
        let result = transpile_control(&control);

        assert!(result.content.contains("it '"));
        assert!(result.content.contains("expect("));
    }

    #[test]
    fn transpile_filename_generation() {
        assert_eq!(control_id_to_filename("sshd-01"), "sshd_01_spec.rb");
        assert_eq!(control_id_to_filename("test_ctrl"), "test_ctrl_spec.rb");
        assert_eq!(control_id_to_filename("CIS-5.2.1"), "CIS_5_2_1_spec.rb");
    }

    #[test]
    fn transpile_source_comment() {
        let control = sample_control();
        let result = transpile_control(&control);

        assert!(result
            .content
            .contains("# Assertion: its('Protocol') { should cmp 2 }"));
    }

    #[test]
    fn transpile_multi_test_control() {
        let mut control = sample_control();
        control.tests.push(InSpecTest {
            resource_type: "file".to_string(),
            resource_args: "/etc/ssh/sshd_config".to_string(),
            matchers: vec![InSpecMatcher {
                property: None,
                expectation: "be_owned_by 'root'".to_string(),
                negated: false,
                raw_line: "it { should be_owned_by 'root' }".to_string(),
            }],
        });

        let result = transpile_control(&control);

        // Should contain both resource comments
        assert!(result.content.contains("# InSpec resource: sshd_config"));
        assert!(result.content.contains("# InSpec resource: file"));
    }

    #[test]
    fn transpile_nist_tag_preserved() {
        let control = sample_control();
        let result = transpile_control(&control);

        assert!(result.content.contains("AC-17(2)"));
        assert!(result.content.contains("SC-8"));
    }

    #[test]
    fn transpile_cis_tag_preserved() {
        let control = sample_control();
        let result = transpile_control(&control);

        assert!(result.content.contains("5.2.1"));
    }

    #[test]
    fn transpile_impact_in_metadata() {
        let mut control = sample_control();
        control.impact = 0.7;
        let result = transpile_control(&control);

        assert!(result.content.contains("metadata[:impact] = 0.7"));
    }

    #[test]
    fn transpile_profile_multiple_controls() {
        let controls = vec![sample_control(), {
            let mut c = sample_control();
            c.id = "sshd-02".to_string();
            c
        }];

        let files = super::transpile_profile(&controls, "ssh-baseline");
        assert_eq!(files.len(), 2);
        assert_eq!(files[0].control_id, "sshd-01");
        assert_eq!(files[1].control_id, "sshd-02");
    }

    #[test]
    fn transpile_determinism_same_output() {
        let control = sample_control();

        let result1 = transpile_control(&control);
        let result2 = transpile_control(&control);

        assert_eq!(result1.content, result2.content);
        assert_eq!(result1.filename, result2.filename);
    }

    #[test]
    fn transpile_determinism_repeated() {
        let control = sample_control();

        // Run 10 times — output must be identical every time
        let baseline = transpile_control(&control).content;
        for _ in 0..10 {
            assert_eq!(transpile_control(&control).content, baseline);
        }
    }

    #[test]
    fn transpile_no_tests_generates_skip() {
        let control = InSpecControl {
            id: "skip-01".to_string(),
            impact: 0.5,
            title: "No Tests".to_string(),
            description: "Control with no tests".to_string(),
            tags: vec![],
            tests: vec![],
            source_file: "test.rb".to_string(),
            source_line: 1,
        };

        let result = transpile_control(&control);
        assert!(result.content.contains("skip 'No automated tests defined for this control'"));
    }

    #[test]
    fn transpile_negated_assertion() {
        let control = InSpecControl {
            id: "neg-01".to_string(),
            impact: 0.5,
            title: "Negated".to_string(),
            description: "Test negation".to_string(),
            tags: vec![],
            tests: vec![InSpecTest {
                resource_type: "package".to_string(),
                resource_args: "'telnet'".to_string(),
                matchers: vec![InSpecMatcher {
                    property: None,
                    expectation: "be_installed".to_string(),
                    negated: true,
                    raw_line: "it { should_not be_installed }".to_string(),
                }],
            }],
            source_file: "test.rb".to_string(),
            source_line: 1,
        };

        let result = transpile_control(&control);
        assert!(result.content.contains("to_not"));
    }

    #[test]
    fn transpile_require_helpers() {
        let control = sample_control();
        let result = transpile_control(&control);

        assert!(result.content.contains("require 'compliance_helpers'"));
    }

    #[test]
    fn format_impact_whole_number() {
        assert_eq!(format_impact(1.0), "1.0");
        assert_eq!(format_impact(0.0), "0.0");
    }

    #[test]
    fn format_impact_decimal() {
        assert_eq!(format_impact(0.7), "0.7");
        assert_eq!(format_impact(0.35), "0.35");
    }

    #[test]
    fn format_tag_value_single() {
        let tag = InSpecTag {
            key: "cis".to_string(),
            values: vec!["5.2.1".to_string()],
        };
        assert_eq!(format_tag_value(&tag), "'5.2.1'");
    }

    #[test]
    fn format_tag_value_array() {
        let tag = InSpecTag {
            key: "nist".to_string(),
            values: vec!["AC-7".to_string(), "SC-8".to_string()],
        };
        assert_eq!(format_tag_value(&tag), "['AC-7', 'SC-8']");
    }

    #[test]
    fn translate_cmp_simple() {
        let (m, v) = translate_expectation("cmp 2");
        assert_eq!(m, "eq");
        assert_eq!(v.unwrap(), "2");
    }

    #[test]
    fn translate_cmp_lte() {
        let (m, v) = translate_expectation("cmp <= 4");
        assert_eq!(m, "be <=");
        assert_eq!(v.unwrap(), "4");
    }

    #[test]
    fn translate_eq() {
        let (m, v) = translate_expectation("eq 'no'");
        assert_eq!(m, "eq");
        assert_eq!(v.unwrap(), "'no'");
    }

    #[test]
    fn translate_match() {
        let (m, v) = translate_expectation("match /5\\.4/");
        assert_eq!(m, "match");
        assert_eq!(v.unwrap(), "/5\\.4/");
    }

    #[test]
    fn translate_be_predicate() {
        let (m, v) = translate_expectation("be_installed");
        assert_eq!(m, "be_installed");
        assert!(v.is_none());
    }

    #[test]
    fn clean_resource_arg_quoted() {
        assert_eq!(clean_resource_arg("'telnet'"), "'telnet'");
    }

    #[test]
    fn clean_resource_arg_unquoted() {
        assert_eq!(clean_resource_arg("telnet"), "'telnet'");
    }
}
